name: Terraform Deploy (dev)

on:
  push:
    branches: [main]

permissions:
  id-token: write       # 🔐 For OIDC authentication
  contents: read        # 📁 Required for checkout

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ROLE_ARN: arn:aws:iam::007695491693:role/github-actions
      ROLE_SESSION_NAME: github-actions-session

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        working-directory: ./env/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: ./env/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./env/dev
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./env/dev
        run: terraform apply --auto-approve
